apiVersion: v1
kind: Secret
metadata:
  namespace: n8n
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: bjhu
  POSTGRES_PASSWORD: bjhuQDEyMw==
  POSTGRES_DB: bjhu
  POSTGRES_NON_ROOT_USER: bjhu
  POSTGRES_NON_ROOT_PASSWORD: bjhuQDEyMw==