apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  labels:
    app: jellyfin
spec:
  type: ClusterIP
  selector:
    app: jellyfin
  ports:
    - name: http
      port: 8096
      targetPort: 8096
    - name: udp-discovery
      port: 7359
      protocol: UDP
      targetPort: 7359
    - name: https
      port: 8920
      targetPort: 8920